### ISSUE TITLE
Error "Title: OpenAI request failed" or "Title: missing article title or text"

### ISSUE THREAD

**Issue by Detzy** [marksverdhei/save-me-a-click-chrome-extension#15]
I am not able to perform any successful prompts with the extension. 
Error is the following: "Title: OpenAI request failed"
Some links in some pages also give the error "Title: missing article title or text"

To reproduce:
Windows 10
npm@9.7.1

---------------

git clone git@github.com:marksverdhei/save-me-a-click-chrome-extension.git
cd save-me-a-click-chrome-extension
npm i
npx webpack

---------------

Add as chrome extension is directed in readme
Generate api key
Add api key to extension
Search for "wikipedia example" by using Google
Right click the link: https://en.wikipedia.org/wiki/Example

My result: "Title: OpenAI request failed"

**Comment by marksverdhei** [comment]
To address the "missing article text", the extension uses newspaper.js under the hood to extract the article title and text. 
Unfortunately, it does not work on every site as being able to extract data from every site is virtually impossible. 

However, upon further investigation, I found that Facebook generates custom urls for links posted, which I think is the main reason why it fails.

**Comment by marksverdhei** [comment]
Make sure you have done the following:
* Added an API key that was created after you had set up a paid openai account
* Refreshed your tab after installing the Chrome extension and set your API key
* When you open the extension popup (by clicking the icon in the top right corner) it should say API key saved!


[Try clicking save me a click on this link. Do you get the same error?](https://www.cnn.com/2023/06/09/entertainment/jurassic-park-anniversary/index.html)

If it still does not work, I would be super happy if you could open the service worker window in the manage extensions tab:

![image](https://github.com/marksverdhei/save-me-a-click-chrome-extension/assets/46672778/0809c898-d23c-4530-a7bb-1e1a8b537a13)

Then, check out what the logged response object contains (yes, i know it's a mess). In the following example, i ran "save me a click" without setting an API key, thus getting the 401 access denied from the Openai API

![image](https://github.com/marksverdhei/save-me-a-click-chrome-extension/assets/46672778/260265ab-d84d-48e0-ad2f-a2e1f1c62cb2)

**Comment by marksverdhei** [comment]
With the most recent version, you should at least be able to see from the interface, whether the issue relates to your API key or something else :)

**Comment by Detzy** [comment]
Cheers! Cant check my setup before monday, but I’ll report back the results then!

**Comment by Detzy** [comment]
Found the issue, which was easy with your new version! All my fault 😳 
I missunderstood the funding model of the API, so I had no available funds to use.
