### ISSUE TITLE
Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by titaenstad** [marksverdhei/save-me-a-click-chrome-extension#24]
Får denne feilen når jeg prøver å installere extensionen 

![image](https://github.com/marksverdhei/save-me-a-click-chrome-extension/assets/42641610/1244bbe1-8dcf-4e39-a8fd-437c737e883c)

**Comment by marksverdhei** [comment]
Saw there was a broken link. We were able to resolve this,

Remember to follow the steps on how to install it

**Comment by titaenstad** [comment]
Used the cloned repo directory instead of the lates release
